// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("MessageTemplates")]
[assembly: AssemblyProductAttribute("MessageTemplates")]
[assembly: AssemblyDescriptionAttribute("The ability to format named string values, and capture the properties")]
[assembly: AssemblyVersionAttribute("1.0.1")]
[assembly: AssemblyFileVersionAttribute("1.0.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.1";
    }
}
